/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package accesoadatos2;

import Negocio.FicherosDatos;
import accesoadatos2.datos.Persona;
import datos.Compra;
import factoria.TiposToXML;
import factoria.ToXMLFactory;
import factoria.ToXMLable;
import java.io.FileReader;
import java.util.LinkedHashMap;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import util.Constantes;

/**
 *
 * @author dam2
 */
public class FramePersona extends javax.swing.JFrame {

    /**
     * Creates new form FramePersona
     */
    ToXMLFactory ft;
    
    public FramePersona() {  
        ft=new ToXMLFactory();
        ToXMLable fac=ft.build(TiposToXML.XSTREAM);
        initComponents();
        leerProperties();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addColumn("ID");
        model.addColumn("NOMBRE");
        LinkedHashMap<Integer, Persona> personas = (LinkedHashMap<Integer, Persona>) fac.fromXML("personas.xml");
        deHashATabla(personas);
        jTable1.setModel(model);
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (jTable1.getSelectedRow() >= 0){
                    jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                    jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                }
            }
        });

    }
    
    private String rutaBD = null;
    private void leerProperties() {
        FileReader file = null;
        Properties p = null;
        try {
            p = new Properties();
            file = new FileReader(Constantes.FICHERO_PROPERTIES);
            p.load(file);
            rutaBD = p.getProperty(Constantes.RUTABD_PROPERTY);
               
            file.close();
        } catch (Exception ex) {
            Logger.getLogger(FramePersona.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BTguarda = new javax.swing.JButton();
        BTelimina = new javax.swing.JButton();
        BTadd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        BotonSI = new javax.swing.JButton();
        BotonNO = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonCrear = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonCargar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonCompras = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        jDialog1.setMinimumSize(new java.awt.Dimension(550, 400));
        jDialog1.setModal(true);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialog1WindowClosing(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Concepto"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        BTguarda.setText("Guardar");
        BTguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTguardaActionPerformed(evt);
            }
        });

        BTelimina.setText("Eliminar compra");
        BTelimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeliminaActionPerformed(evt);
            }
        });

        BTadd.setText("Añadir compra");
        BTadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaddActionPerformed(evt);
            }
        });

        jLabel3.setText("...");

        jLabel4.setText("Compras del usuario:");

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(BTadd)
                .addGap(65, 65, 65)
                .addComponent(BTelimina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTguarda)
                .addGap(62, 62, 62))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(206, 206, 206))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTadd)
                    .addComponent(BTelimina)
                    .addComponent(BTguarda))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(350, 200));
        jDialog2.setModal(true);

        BotonSI.setText("Sí");
        BotonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSIActionPerformed(evt);
            }
        });

        BotonNO.setText("No");
        BotonNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNOActionPerformed(evt);
            }
        });

        jLabel6.setText("¿Desea salir realmente de la ventana de compras?");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BotonSI)
                        .addGap(94, 94, 94)
                        .addComponent(BotonNO))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel6)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSI)
                    .addComponent(BotonNO))
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setText("ID");

        jTextField2.setText("Nombre");

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        BotonCrear.setText("Crear");
        BotonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearActionPerformed(evt);
            }
        });

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonBorrar.setText("Borrar");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonCargar.setText("Cargar");
        BotonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarActionPerformed(evt);
            }
        });

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonCompras.setText("Compras");
        BotonCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprasActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAXB", "XSTREAM" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BotonCargar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonGuardar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BotonCrear)
                                .addGap(18, 18, 18)
                                .addComponent(BotonCompras)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonLimpiar)
                            .addComponent(BotonBorrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCompras)
                    .addComponent(BotonCrear)
                    .addComponent(BotonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCargar)
                    .addComponent(BotonGuardar)
                    .addComponent(BotonLimpiar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        model.addRow(new Object[]{jTextField1.getText(), jTextField2.getText()});
    }//GEN-LAST:event_BotonCrearActionPerformed
    private LinkedHashMap<Integer, Persona> deTablaAHash() {
        LinkedHashMap<Integer,Persona> personas =  new LinkedHashMap<>();
        Persona p = null;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            p = new Persona(
                    Integer.parseInt((String) jTable1.getModel().getValueAt(i, Constantes.COLUMN_ID).toString()),
                    (String) jTable1.getModel().getValueAt(i, Constantes.COLUMN_NOMBRE));
            personas.put(p.getId(), p);
        }
        return personas;
    }
    
    private LinkedHashMap<Integer, Compra> deTablaAHash2() {
        LinkedHashMap<Integer,Compra> compras =  new LinkedHashMap<>();
        Compra c = null;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            c = new Compra(
                    Integer.parseInt((String) jTable2.getModel().getValueAt(i, Constantes.COLUMN_ID).toString()),
                    (String) jTable2.getModel().getValueAt(i, Constantes.COLUMN_NOMBRE));
            compras.put(i, c);
        }
        return compras;
    }

    private void deHashATabla(LinkedHashMap<Integer, Persona> personas) {
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());

        for (Integer in :personas.keySet())
            model.addRow(new Object[]{personas.get(in).getId(), personas.get(in).getNombre()});
        /*for (Persona p : personas) {
            model.addRow(new Object[]{p.getId(), p.getNombre()});
        }*/
    }
    
    private void deHashATabla2(LinkedHashMap<Integer, Compra> compras) {
        DefaultTableModel model = ((DefaultTableModel) jTable2.getModel());

        for (Integer in :compras.keySet())
            model.addRow(new Object[]{compras.get(in).getCantidad(), compras.get(in).getConcepto()});
        /*for (Compra c : compras) {
            model.addRow(new Object[]{c.getCantidad(), c.getConcepto()});
        }*/
    }

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
        
        for (int i = jTable1.getRowCount()-1;i>=0; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>=0){
            DefaultTableModel model = ((DefaultTableModel) jTable1.getModel());
            int[] rows = jTable1.getSelectedRows();
            
            for(int i=0;i<jTable1.getRowCount();i++){
                model.removeRow(rows[i]-i);
            }
        }
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
        // TODO add your handling code here:
        ft=new ToXMLFactory();
        ToXMLable fac=ft.build(TiposToXML.XSTREAM);
        String nombre = "personas.xml";
        deHashATabla((LinkedHashMap<Integer, Persona>) fac.fromXML(nombre));
    }//GEN-LAST:event_BotonCargarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:        
        ft=new ToXMLFactory();
        ToXMLable fac=ft.build(TiposToXML.XSTREAM);
        String nombre = "personas.xml";
        fac.toXML(nombre, deTablaAHash());
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprasActionPerformed
        // TODO add your handling code here:
        ft=new ToXMLFactory();
        ToXMLable fac=ft.build(TiposToXML.valueOf(jComboBox1.getName()));
        if(jTable1.getSelectedRow()>=0){
            jLabel3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            jLabel5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            DefaultTableModel mod = ((DefaultTableModel) jTable2.getModel());
            for (int i = jTable2.getRowCount()-1;i>=0; i--) {
                mod.removeRow(i);
            }
            String nombre = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            FicherosDatos fd = new FicherosDatos();
            deHashATabla2((LinkedHashMap<Integer, Compra>) fac.fromXML(nombre+".xml"));
            jDialog1.setVisible(true);
        }
    }//GEN-LAST:event_BotonComprasActionPerformed

    private void BTaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) jTable2.getModel();
        
        mod.addRow(new Object[]{1, "Concepto"});
    }//GEN-LAST:event_BTaddActionPerformed

    private void BTeliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeliminaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = ((DefaultTableModel) jTable2.getModel());
        
        mod.removeRow(jTable2.getSelectedRow());
    }//GEN-LAST:event_BTeliminaActionPerformed

    private void BTguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTguardaActionPerformed
        // TODO add your handling code here:          
        ft=new ToXMLFactory();
        ToXMLable fac=ft.build(TiposToXML.XSTREAM);
        fac.toXML(jLabel3.getText()+".xml", deTablaAHash2());
    }//GEN-LAST:event_BTguardaActionPerformed

    private void jDialog1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowClosing
        // TODO add your handling code here:
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jDialog1WindowClosing

    private void BotonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSIActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
        jDialog1.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_BotonSIActionPerformed

    private void BotonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNOActionPerformed
        // TODO add your handling code here:
        jDialog2.setVisible(false);
        jDialog1.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_BotonNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FramePersona().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTadd;
    private javax.swing.JButton BTelimina;
    private javax.swing.JButton BTguarda;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonCargar;
    private javax.swing.JButton BotonCompras;
    private javax.swing.JButton BotonCrear;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonNO;
    private javax.swing.JButton BotonSI;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
